//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "CompHandler.hh"
#include "SmartURServer.hh"

#include <iostream>

// include communication objects
#include <DomainVision/Comm3dPointCloud.hh>
#include <CommBasicObjects/CommBaseState.hh>
#include <CommRobotinoObjects/CommDigitalInputEventParameter.hh>
#include <CommRobotinoObjects/CommDigitalInputEventResult.hh>
#include <CommRobotinoObjects/CommDigitalInputEventState.hh>
#include <CommManipulatorObjects/CommManipulatorEventParameter.hh>
#include <CommManipulatorObjects/CommManipulatorEventResult.hh>
#include <CommManipulatorObjects/CommManipulatorEventState.hh>
#include <CommManipulatorObjects/CommManipulatorId.hh>
#include <CommManipulatorObjects/CommManipulatorRequestScan3d.hh>
#include <CommManipulatorObjects/CommManipulatorTrajectory.hh>
#include <CommBasicObjects/CommMobileLaserScan.hh>
#include <CommManipulatorObjects/CommMobileManipulatorState.hh>
#include <CommRobotinoObjects/CommRobotinoIOValues.hh>
#include <CommManipulatorObjects/CommScanEventState.hh>
#include <CommBasicObjects/CommVoid.hh>


void CompHandler::onStartup() 
{
	std::cout << "startup - put your startupCode in CompHandler::onStartup()!!!\n";

	Smart::StatusCode status;

	// Start all services. If you need manual control, use the content of this function to
	// connect and start each service individually, e.g:
	// COMP->connectMyPortName("SmartExampleComponent", "examplePort");
	status = COMP->connectAndStartAllServices();
	
	// Start all tasks. If you need manual control, use the content of this function to
	// start each task individually.
	COMP->startAllTasks();
	
	// Start all timers. If you need manual control, use the content of this function to
	// start each timer individually.
	COMP->startAllTimers();
	
	// Notify the component that setup/initialization is finished.
	// You may move this function to any other place.
	COMP->setStartupFinished(); 
}

void CompHandler::onShutdown() 
{
	std::cout << "shutdown - put your cleanup code in CompHandler::onShutdown()!!!\n";
	
}
