//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _SCAN3DEVENTSERVER_EVENT_TEST_HANDLER_USER_HH
#define _SCAN3DEVENTSERVER_EVENT_TEST_HANDLER_USER_HH
		
#include "Scan3dEventServerEventTestHandlerCore.hh"

class Scan3dEventServerEventTestHandler : public Scan3dEventServerEventTestHandlerCore
{
public:
	virtual bool testEvent(
		CommBasicObjects::CommVoid &p,
		CommManipulatorObjects::CommManipulatorId &r,
		const CommManipulatorObjects::CommScanEventState &s
	) throw();
};
#endif
